db_user: librenms
db_port: 3306
librenms_required_packages:
  - curl 
  - composer 
  - fping 
  - git 
  - graphviz 
  - imagemagick 
  - mariadb-client 
  - mariadb-server 
  - memcached
  - mtr-tiny 
  - nginx-full 
  - nmap 
  - php7.2-cli 
  - php7.2-curl 
  - php7.2-fpm 
  - php7.2-gd 
  - php7.2-json 
  - php7.2-mbstring 
  - php7.2-mysql 
  - php7.2-snmp 
  - php7.2-xml 
  - php7.2-zip 
  - python-memcache 
  - python-mysqldb 
  - rrdtool 
  - snmp 
  - snmpd 
  - whois
snmp_contact: Support
snmp_location: 123 fake street
snmp_v2_community: readonly